### ISSUE TITLE
wants data for running the code

### ISSUE THREAD

**Issue by agl71** [A5-015/flyway#1]
Dear sir:

The following data in your source codes can not be downloaded. 
Could you add them into .\src\dataset\.   
 
"final_network_sniffing_data.csv";"oui.csv","exclude_list.csv"

Best Regards;

Jackson

**Comment by agl71** [comment]
and the "network_traffic_data.csv".
Best Regards;

**Comment by woswos** [comment]
Hi,

Let me see if I still have them but they were quite large files as far as I remember.

**Comment by agl71** [comment]
Thank you any way! 
By the way, there are some csv files in .\src\dataset\. 
Could you tell me what is the meaning  of 'cid', 'eth','mam','manid', which might be related to the user of MAC addresses.
Your kindness will be great appreciated!
Best Regards;

**Comment by agl71** [comment]
Dear Sir:

I have a question with the paper of "Flyway: Predicting Foot Traffic in Open Spaces on Campus", which is in .\report\interim_report\Nishant_Barkin_Final_Project_Interim_Report.pdf.
In Formula (2), the transfer probability of (i-o)  is related the sum(from in to out), 
but if we did't  know the ground truth , how could we know the SUM(from in to out) ?
by the way, No answer was found after I searched the source code 'flyway_traffic_model.ipynb' .

Best Regards;    

![formula2](https://user-images.githubusercontent.com/12965632/99644086-731aff00-2a88-11eb-9690-0f49f6a7a4c1.png)

**Comment by woswos** [comment]
Sorry for the delay @agl71

1) I cannot share the whole network sniffing data since it contains a lot of private information but it follows the following format:

frame.number,frame.time,wlan.addr,wlan.ta,wlan.ra,wlan.sa,wlan.da,wlan.bssid,wlan.fc.type,wlan.fc.type_subtype,radiotap.channel.freq,radiotap.datarate,radiotap.dbm_antsignal
"1","Nov 10, 2019 17:44:56.905180894 +04","ff:ff:ff:ff:ff:ff","34:97:f6:ac:9c:10","ff:ff:ff:ff:ff:ff","34:97:f6:ac:9c:10","ff:ff:ff:ff:ff:ff","34:97:f6:ac:9c:10","0","8","2457","1","-45"

You can sniff your own data using Wireshark in the format specified above. The final version file was the one that dropped the unused column, as far as I remember. You can see which columns were dropped in the Jupyter Notebook file (or possibly in the paper)

2) You can check [this Wireshark Cheatsheet](https://vichhaiy.files.wordpress.com/2018/01/wireshark_802-11_filters_-_reference_sheet-pdf-1516608860417-e1516608947978.png) to understand what each column means in the sniffing data.
3) oui.csv is [this file](http://standards-oui.ieee.org/oui.txt) but in csv format.
4) exclude_list.csv is list of devices to exclude from sniffing, I don't have it and you might not need it at all.
5) I believe @niniack can answer the question related to the formula better.
6) I think we used 'cid', 'eth', 'mam', and 'manid' files to determine which devices were mobile phones and which ones were not. For example, Dell doesn't have phones, so the MAC addresses registered under Dell are not mobile phones.

**Comment by agl71** [comment]
@woswos 
Thank you very much! You are so kind.

agl71

**Comment by agl71** [comment]
@woswos 
Thank you very much! You are so kind.
@niniack  

agl71

**Comment by agl71** [comment]
@woswos  Thank you much! You are so kind!
@niniack  I think that  the the ground truth should be known when we calculate transfer probability  of  (i-o) in formula 2 . But I did not find any parts of source code of it .

**Comment by niniack** [comment]
@agl71 Hey, thanks for checking Flyway out :) I looked through the report and found the equation you are referring to. 

I am not sure if you have easy access to the text but if you read around the equation, this equation was actually something we referenced from another paper titled _Occupancy prediction through markov basedfeedback recurrent neural network (m-frnn) al-gorithm with wifi probe technology_ by Wang et. al. We do not make the claim that we used this equation or any of their methodology directly!

In fact, on our constraints section on the same page, we say 

> The work done in Wang. et. al. was a source of inspiration for us to explore machine learning models used in time-series forecasting. However, the specifics of their approach did not align with our project as they had a greater number of validational resources at hand.

We do not use an approach that involves a transfer probability matrix!

The ground truth of our model is not actually the number of people because that would have involved us counting the number of people as part of data collection (which was not feasible for us). Our ground truth is the number of devices we pick up in our scanning!

Happy to answer more questions.

**Comment by agl71** [comment]
Thank you very much!

**Comment by agl71** [comment]
@niniack Hay
Thank you very much!
Best Regards;

**Comment by niniack** [comment]
Glad we could help
